"""
Axoloti Terminal — Настройки приложения.

Все значения читаются через os.getenv.
"""

import os
from typing import Optional

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
APP_ENV = os.getenv("APP_ENV", "development")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "axoloti-dev-secret-change-me-in-production")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
# Срок сессии оператора: по умолчанию 180 дней (можно переопределить через JWT_ACCESS_TOKEN_EXPIRE_MINUTES).
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(
    os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", str(180 * 24 * 60))
)
TELEGRAM_WEBHOOK_AUTOMATION_ENABLED = os.getenv("TELEGRAM_WEBHOOK_AUTOMATION_ENABLED", "true").lower() == "true"
TELEGRAM_WEBHOOK_PATH = os.getenv("TELEGRAM_WEBHOOK_PATH", "/api/v1/webhooks/telegram")
TELEGRAM_WEBHOOK_PUBLIC_URL = os.getenv("WEBHOOK_DOMAIN", os.getenv("TELEGRAM_WEBHOOK_PUBLIC_URL", "")).strip().rstrip("/")
TELEGRAM_TUNNEL_PORT = int(os.getenv("TELEGRAM_TUNNEL_PORT", "8000"))
TELEGRAM_TUNNEL_STARTUP_TIMEOUT_SECONDS = int(os.getenv("TELEGRAM_TUNNEL_STARTUP_TIMEOUT_SECONDS", "60"))
TELEGRAM_TUNNEL_RESTART_DELAY_SECONDS = int(os.getenv("TELEGRAM_TUNNEL_RESTART_DELAY_SECONDS", "5"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") or None
# ID промпта из OpenAI Dashboard (Responses API). Fallback: OPENAI_ASSISTANT_ID для совместимости.
OPENAI_RESPONSE_ID = (
    os.getenv("OPENAI_RESPONSE_ID") or os.getenv("OPENAI_ASSISTANT_ID") or None
)

DEFAULT_ADMIN_USER = os.getenv("DEFAULT_ADMIN_USER", "admin")
DEFAULT_ADMIN_PASSWORD = os.getenv("DEFAULT_ADMIN_PASSWORD", "admin")


class Settings:
    """Обёртка для совместимости с кодом, использующим settings.ATTR."""

    TELEGRAM_BOT_TOKEN: str = TELEGRAM_BOT_TOKEN
    APP_ENV: str = APP_ENV
    JWT_SECRET_KEY: str = JWT_SECRET_KEY
    JWT_ALGORITHM: str = JWT_ALGORITHM
    JWT_ACCESS_TOKEN_EXPIRE_MINUTES: int = JWT_ACCESS_TOKEN_EXPIRE_MINUTES
    TELEGRAM_WEBHOOK_AUTOMATION_ENABLED: bool = TELEGRAM_WEBHOOK_AUTOMATION_ENABLED
    TELEGRAM_WEBHOOK_PATH: str = TELEGRAM_WEBHOOK_PATH
    TELEGRAM_WEBHOOK_PUBLIC_URL: str = TELEGRAM_WEBHOOK_PUBLIC_URL
    TELEGRAM_TUNNEL_PORT: int = TELEGRAM_TUNNEL_PORT
    TELEGRAM_TUNNEL_STARTUP_TIMEOUT_SECONDS: int = TELEGRAM_TUNNEL_STARTUP_TIMEOUT_SECONDS
    TELEGRAM_TUNNEL_RESTART_DELAY_SECONDS: int = TELEGRAM_TUNNEL_RESTART_DELAY_SECONDS
    OPENAI_API_KEY: Optional[str] = OPENAI_API_KEY
    OPENAI_RESPONSE_ID: Optional[str] = OPENAI_RESPONSE_ID
    DEFAULT_ADMIN_USER: str = DEFAULT_ADMIN_USER
    DEFAULT_ADMIN_PASSWORD: str = DEFAULT_ADMIN_PASSWORD


settings = Settings()
